Fix some of the failing tests
1) Fixing failing test `FlatObjectFiledMapperTests.testExistsQueryMinimalMapping`:

```
Can not write a field name, expecting a value
com.fasterxml.jackson.core.JsonGenerationException: Can not write a field name, expecting a value
	at __randomizedtesting.SeedInfo.seed([163E47FC8A06B681:6F031AC0DD5FD2A1]:0)
	at app//com.fasterxml.jackson.core.JsonGenerator._reportError(JsonGenerator.java:2733)
	at app//com.fasterxml.jackson.core.json.UTF8JsonGenerator.writeFieldName(UTF8JsonGenerator.java:217)
	at app//org.opensearch.common.xcontent.json.JsonXContentGenerator.writeFieldName(JsonXContentGenerator.java:195)
	at app//org.opensearch.common.xcontent.XContentBuilder.field(XContentBuilder.java:298)
	at app//org.opensearch.flatobject.mapper.FlatObjectFieldMapperTests.writeFieldValue(FlatObjectFieldMapperTests.java:45)
	at app//org.opensearch.index.mapper.MapperTestCase.writeField(MapperTestCase.java:87)
	at app//org.opensearch.index.mapper.MapperServiceTestCase.source(MapperServiceTestCase.java:184)
	at app//org.opensearch.index.mapper.MapperTestCase.assertExistsQuery(MapperTestCase.java:108)
	at app//org.opensearch.index.mapper.MapperTestCase.testExistsQueryMinimalMapping(MapperTestCase.java:103)
```

The `writeFieldValue` needs to construct a real object.

2) Add "missing" GeoShape field mapper plugin for `FlatObjectQueryBuilderTests`:

This is really a hack, which is unfortunately required.
For further info see the following ticket I opened:
<https://github.com/opensearch-project/OpenSearch/issues/6322>

We are able to start fixing individual failing tests.

Signed-off-by: Lukáš Vlček <lukas.vlcek@aiven.io>